apiVersion: v1alpha1.example.com/v1alpha1
kind: EnvoyProxyTemplate
metadata:
  name: example-envoyproxytemplate
spec:
  image: "envoyproxy/envoy:v1.30-latest"
  httpFilters:
    - name: filter1
      typedConfig:
        "@type": type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthz
        grpc_service:
          envoy_grpc:
            cluster_name: ext-authz

          # Default is 200ms; override if your server needs e.g. warmup time.
          timeout: 0.5s
        include_peer_certificate: true
    - name: filter2
      typedConfig:
        "@type": type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthz
        grpc_service:
          envoy_grpc:
            cluster_name: ext-authz2
        with_request_body:
          max_request_bytes: 1024
          allow_partial_message: true
          pack_as_bytes: true
    - name: filter3
      typedConfig:
        "@type": type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthz
        grpc_service:
          envoy_grpc:
            cluster_name: ext-authz2
        with_request_body:
          max_request_bytes: 1024
          allow_partial_message: true
          pack_as_bytes: true
    - name: filter4
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.filters.http.golang.v3alpha.Config
        library_id: my-configurable-plugin-id
        library_path: "lib/my_configurable_plugin.so"
        plugin_name: my_configurable_plugin
        plugin_config:
          "@type": type.googleapis.com/xds.type.v3.TypedStruct
          value:
            foo: default_foo
    - name: filter5
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
