apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kode-operator.fullname" . }}-kodetemplate-editor-role
  labels:
  {{- include "kode-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - kode.jacero.io
  resources:
  - kodetemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kode.jacero.io
  resources:
  - kodetemplates/status
  verbs:
  - get