# permissions for end users to view envoyproxyclusterconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kode-operator
    app.kubernetes.io/managed-by: kustomize
  name: envoyproxyclusterconfig-viewer-role
rules:
- apiGroups:
  - kode.jacero.io
  resources:
  - envoyproxyclusterconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kode.jacero.io
  resources:
  - envoyproxyclusterconfigs/status
  verbs:
  - get
