# permissions for end users to view kodetemplates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kode-operator
    app.kubernetes.io/managed-by: kustomize
  name: kodetemplate-viewer-role
rules:
- apiGroups:
  - kode.jacero.io
  resources:
  - kodetemplates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kode.jacero.io
  resources:
  - kodetemplates/status
  verbs:
  - get
