# permissions for end users to view kodeclustertemplates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kode-operator
    app.kubernetes.io/managed-by: kustomize
  name: kodeclustertemplate-viewer-role
rules:
- apiGroups:
  - kode.jacero.io
  resources:
  - kodeclustertemplates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kode.jacero.io
  resources:
  - kodeclustertemplates/status
  verbs:
  - get
