---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kode.jacero.io
  resources:
  - envoyproxies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kode.jacero.io
  resources:
  - envoyproxies/finalizers
  verbs:
  - update
- apiGroups:
  - kode.jacero.io
  resources:
  - envoyproxies/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - kode.jacero.io
  resources:
  - kodes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kode.jacero.io
  resources:
  - kodes/finalizers
  verbs:
  - update
- apiGroups:
  - kode.jacero.io
  resources:
  - kodes/status
  verbs:
  - get
  - patch
  - update
