# permissions for end users to view webtoptemplates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kode-operator
    app.kubernetes.io/managed-by: kustomize
  name: webtoptemplate-viewer-role
rules:
- apiGroups:
  - kode.jacero.io
  resources:
  - webtoptemplates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kode.jacero.io
  resources:
  - webtoptemplates/status
  verbs:
  - get
