apiVersion: kode.jacero.io/v1alpha1
kind: EnvoyProxyTemplate
metadata:
  labels:
    app.kubernetes.io/name: kode-operator
    app.kubernetes.io/managed-by: kustomize
  name: envoyproxytemplate-sample
spec:
  image: envoyproxy/envoy:v1.30-latest
  httpFilters:
    - name: envoy.filters.http.ext_authz
      typed_config:
        '@type': type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthz
        with_request_body:
          max_request_bytes: 8192
          allow_partial_message: true
        failure_mode_allow: false
        grpc_service:
          envoy_grpc:
            cluster_name: ext_authz-opa-service
          timeout: 0.250s
        transport_api_version: V3
    - name: envoy.filters.http.router
      typed_config:
        '@type': type.googleapis.com/envoy.extensions.filters.http.router.v3.Router