apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kode.fullname" . }}-envoyproxyclusterconfig-editor-role
  labels:
  {{- include "kode.labels" . | nindent 4 }}
rules:
- apiGroups:
  - kode.jacero.io
  resources:
  - envoyproxyclusterconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kode.jacero.io
  resources:
  - envoyproxyclusterconfigs/status
  verbs:
  - get