name: Build & Publish container images to GHCR

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  build-and-publish:
    permissions:
      packages: write
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.22'

    - name: Install dependencies
      run: make $(LOCALBIN)

    - name: Run Tests
      run: make test

    - name: Build and push Docker image using Make
      run: make docker-buildx IMG=ghcr.io/${{ github.repository }}/kode-operator:${{ github.ref_name }}

    - name: Log out from GitHub Container Registry
      run: docker logout ghcr.io
