name: Build & Publish container images to GHCR

on:
  push:
    branches:
      - main
      - 'feature/*'
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      server-tag: ${{ steps.build.outputs.server-tag }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        id: prepare-build
        run: |
          export PLATFORMS="linux/arm64,linux/amd64,linux/s390x,linux/ppc64le"
          sed -e '1 s/\(^FROM\)/FROM --platform=\$\{BUILDPLATFORM\}/; t' -e ' 1,// s//FROM --platform=\$\{BUILDPLATFORM\}/' Dockerfile > Dockerfile.cross
          cat Dockerfile.cross

      - name: Multi-stage Docker Build
        id: build
        uses: firehed/multistage-docker-build-action@v1.7.0
        with:
          dockerfile: Dockerfile
          repository: ghcr.io/${{ github.repository }}/kode-operator
          stages: build,publish
          server-stage: publish
          tag-latest-on-default: false

  publish:
    needs: build
    permissions:
      packages: write
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ${{ needs.build.outputs.server-tag }}

    steps:
      - run: echo "${IMAGE_TAG}"

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        if: (github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository) && github.actor != 'dependabot[bot]'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull built image from build stage
        run: docker pull ghcr.io/${{ github.repository }}/kode-operator:${{ env.IMAGE_TAG }}

      - name: Tag and push Docker image
        if: (github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository) && github.actor != 'dependabot[bot]'
        run: |
          if [[ ${{ github.ref }} == refs/tags/v*.*.* ]]; then
            TAG=${{ github.ref_name }}
            MAJOR=$(echo $TAG | cut -d. -f1)
            MAJOR_MINOR=$(echo $TAG | cut -d. -f1-2)
            docker tag ghcr.io/${{ github.repository }}/kode-operator:${{ env.IMAGE_TAG }} ghcr.io/${{ github.repository }}/kode-operator:$TAG
            docker tag ghcr.io/${{ github.repository }}/kode-operator:${{ env.IMAGE_TAG }} ghcr.io/${{ github.repository }}/kode-operator:latest
            docker tag ghcr.io/${{ github.repository }}/kode-operator:${{ env.IMAGE_TAG }} ghcr.io/${{ github.repository }}/kode-operator:$MAJOR
            docker tag ghcr.io/${{ github.repository }}/kode-operator:${{ env.IMAGE_TAG }} ghcr.io/${{ github.repository }}/kode-operator:$MAJOR_MINOR
            docker push ghcr.io/${{ github.repository }}/kode-operator:$TAG
            docker push ghcr.io/${{ github.repository }}/kode-operator:latest
            docker push ghcr.io/${{ github.repository }}/kode-operator:$MAJOR
            docker push ghcr.io/${{ github.repository }}/kode-operator:$MAJOR_MINOR
          else
            BRANCH=$(echo ${{ github.ref_name }} | sed 's/\//-/g')
            docker tag ghcr.io/${{ github.repository }}/kode-operator:${{ env.IMAGE_TAG }} ghcr.io/${{ github.repository }}/kode-operator:$BRANCH
            docker push ghcr.io/${{ github.repository }}/kode-operator:$BRANCH
          fi

      - name: Log out from GitHub Container Registry
        if: (github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository) && github.actor != 'dependabot[bot]'
        run: docker logout ghcr.io
