name: Build & Publish Helm Charts to GHCR

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  build-and-publish-helm-charts:
    permissions:
      packages: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
          go install sigs.k8s.io/kustomize/kustomize/v5@latest
          go install github.com/arttor/helmify/cmd/helmify@latest

      - name: Extract version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

      - name: Update Chart.yaml for kode-crd
        run: |
          sed -i "s/PLACEHOLDER_VERSION/${{ env.VERSION }}/g" helm-charts/kode-crd/Chart.yaml
          helm package helm-charts/kode-crd --version ${{ env.VERSION }}

      - name: Update Chart.yaml for kode
        run: |
          sed -i "s/PLACEHOLDER_VERSION/${{ env.VERSION }}/g" helm-charts/kode/Chart.yaml
          helm package helm-charts/kode --version ${{ env.VERSION }}

      - name: Push kode-crd chart
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | helm registry login -u ${{ github.actor }} ghcr.io --password-stdin
          helm push kode-crd-${{ env.VERSION }}.tgz oci://ghcr.io/${{ github.repository_owner }}

      - name: Push kode chart
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | helm registry login -u ${{ github.actor }} ghcr.io --password-stdin
          helm push kode-${{ env.VERSION }}.tgz oci://ghcr.io/${{ github.repository_owner }}

      - name: Log out from GitHub Container Registry
        run: helm registry logout ghcr.io
