name: Publish Helm Charts to GHCR

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Extract version from tag
        id: get_version
        # run: echo "::save-state name=version::${GITHUB_REF/refs\/tags\//}"¨
        run: echo "VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_OUTPUT

      - name: Update Chart.yaml for kode-operator-crd
        run: |
          VERSION=${{ steps.get_version.outputs.version }}
          sed -i "s/PLACEHOLDER_VERSION/$VERSION/" helm-charts/kode-operator-crd/Chart.yaml

      - name: Package kode-operator-crd chart
        run: |
          export VERSION=${{ steps.get_version.outputs.version }}
          helm package helm-charts/kode-operator-crd --version $VERSION
          cat 
          helm push kode-operator-crd-$VERSION.tgz oci://ghcr.io/${{ github.repository_owner }}

      - name: Update Chart.yaml for kode-operator
        run: |
          export VERSION=${{ steps.get_version.outputs.version }}
          sed -i "s/PLACEHOLDER_VERSION/$VERSION/" helm-charts/kode-operator/Chart.yaml

      - name: Package kode-operator chart
        run: |
          export VERSION=${{ steps.get_version.outputs.version }}
          helm package helm-charts/kode-operator --version $VERSION
          helm push kode-operator-$VERSION.tgz oci://ghcr.io/${{ github.repository_owner }}
