name: Publish Helm Charts to GHCR

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Extract version from tag
        id: get_version
        run: echo "::set-output name=version::${GITHUB_REF/refs\/tags\//}"

      - name: Update Chart.yaml for kode-operator-crd
        run: |
          version=${{ steps.get_version.outputs.version }}
          sed -i "s/PLACEHOLDER_VERSION/$version/" helm-charts/kode-operator-crd/Chart.yaml

      - name: Package kode-operator-crd chart
        run: |
          version=${{ steps.get_version.outputs.version }}
          helm package helm-charts/kode-operator-crd --version $version
          helm chart save kode-operator-crd-$version.tgz ghcr.io/${{ github.repository_owner }}/kode-operator-crd:$version
          helm chart push ghcr.io/${{ github.repository_owner }}/kode-operator-crd:$version

      - name: Update Chart.yaml for kode-operator
        run: |
          version=${{ steps.get_version.outputs.version }}
          sed -i "s/PLACEHOLDER_VERSION/$version/" helm-charts/kode-operator/Chart.yaml

      - name: Package kode-operator chart
        run: |
          version=${{ steps.get_version.outputs.version }}
          helm package helm-charts/kode-operator --version $version
          helm chart save kode-operator-$version.tgz ghcr.io/${{ github.repository_owner }}/kode-operator:$version
          helm chart push ghcr.io/${{ github.repository_owner }}/kode-operator:$version
