name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Install Git-cliff
        run: |
          curl -sL https://github.com/orhun/git-cliff/releases/download/v0.5.0/git-cliff-x86_64-unknown-linux-gnu.tar.gz | tar xz
          sudo mv git-cliff /usr/local/bin/

      - name: Generate Changelog
        id: changelog
        run: git cliff -c cliff.toml -o CHANGELOG.md

      - name: Get the release notes
        id: notes
        run: |
          export RELEASE_NOTES=$(git cliff -c cliff.toml -o -)
          echo "notes=$RELEASE_NOTES" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: ${{ steps.notes.outputs.notes }}
          draft: false
          prerelease: false
